# Generated by Django 4.2.16 on 2024-11-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='create_date',
        ),
    ]
