# Generated by Django 4.2.16 on 2024-11-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intro_app",
            "0002_remove_user_isadmin_remove_user_username_user_admin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
